language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "UbI4OnNVyPc1CTQk1IpofOnL2BTS2DfgHC+VmKrQweiJpq3833tjAonbtal0QbqCZ9ZRxXMIkMlY8bodPbHTV2TBsBYOF6HpbYYASFCCLchamLledc2NhtWr7iFBN+owuOqIhK235U/Gl5LOmHaGvQNw4gjpXelkQIjOC1WIRH0C83dXyb7fGRrEG6Dhp4FKPqpARUeEKPprSecq1077Ah+bw6UIQAD3fUAxoFTm9DA9icyezYjTHmhLlaSXSEIgqG2P9xHdvvT16+alTyaXY3t2+E1E8iBjlOzspwPikgMyv8IW0DQgj4BsIK31ugMRYNC6+28CF9/c5H/Rs9oiIaOjnBC0fmlazBbqyHKoR6lfwuWBjpfA2esrPiahaJqlwghRxCsKHe8HA3FqDORzGHqL/Q67uPjcTn7zyKddeFc9QgBbuH853BN3ClAkzApP6Q3c/6YsSOjHLyL0sQ7Vmt5pfaLad3Llza1lUd64dxENlqHoAqabKn/MiXA8pYCv2k9FC1QM/EYF6YJSrBQwIClXYzYPiT5t0yE1SIIZywhMN9x47vjb9WiZsXJPTX6SFD4UV0OdXP/sxFKzKipg7MjfZKSvpx75pBjOx+iN3uqIW9zp9urIctMsSthvuvhcSPd1IbeiOEitxJEiqyWGnwP++LKlbM4BACjsaqbBwLg="
  matrix:
    # flo account
    # to generate yours : travis encrypt KONNECTOR_CONFIG=\'"`cat konnector-dev-config.json | tr -d '\n'`"\' -r konnectors/cozy-konnector-free
    - secure: "uxrcd5AhXWNX4zTeI2y7QTD4b44rU0dOfl1q0+AIrOlBb47TfNuaKbeHZQ1hFwOBnhZV9CTkPU0Jgw5tVuYmsn21xjuUpcmf3kfvPnuPxoGMepPVkAw1LeQwyx706H4XK27o1h5RwwjfWQnbEcQbbBP2y9ACVP940NUGQcZ/hDQUe2QyO0RVxjzuE2hHXZVjlc65V6zvZuwo0aJaaywZ8POrepu/o6DZp5XIaLVeREzjEhACXXfkbgyL1O0pPNAdWtLfFRa7MESWftylsYUtPy3jXE5Q+iVz0ymQ3wJP8WBK95VYGQRZ3erpw937Kup4TAcH6PwIz8Ap4TExC2JowEbFG3nQw/IaYvdAa5lKAl5TvTrT+E58kHFFo7Tq9uAcUj6+yH2Zfn8oE2TZh24AQxVSP1x3gMDppLkskZktW27dsfnj2i4kCRpaCjXhNxj2EH9xx4KRZOTG8mYGBh+PnML/6gdaektaUWJwhSWZaImvx5Zhj2gpM3Smp1i6/ufjDilNvdCGCqMoFirCEOhC9PIeqVYK7OOvdi/goOIkgphDln2G1Gev2/ch+SzapGqcHbAsezycmau6urOQ09yLxNSPROdUcvre9/U0MfDjn73cNJsqHXtDY6BDRqzyXkFHjvoQOqFQ0lplhYiWWtbXRiPOLpasVwt9lqdYUhpZ8OQ="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-free
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-free
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
